export const ADD_TO_PORTFOLIO = 'ADD_TO_PORTFOLIO';
export const REMOVE_FROM_PORTFOLIO = 'REMOVE_FROM_PORTFOLIO';
export const REFRESH_STOCK = 'REFRESH_STOCK';
export const REFRESH_HISTORY = 'REFRESH_HISTORY';
