export const ADD_TO_PORTFOLIO = 'ADD_TO_PORTFOLIO';
export const REMOVE_FROM_PORTFOLIO = 'REMOVE_FROM_PORTFOLIO';
export const REFRESH_HISTORY = 'REFRESH_HISTORY';
export const REFRESH_INTRADAY = 'REFRESH_INTRADAY';
export const REFRESH_DAILY = 'REFRESH_DAILY';
export const REFRESH_WEEK = 'REFRESH_WEEK';
export const REFRESH_MONTHLY = 'REFRESH_MONTHLY';
