const QUOTE_ACT = "IBM";
const QUOTE_ACT_GAINS = "PETR4.SA";
const QUOTE_ACT_COMPARE = "TESO";
const INVALID_QUOTE_ACT = "TESO3";
const LIST_QUOTE_COMPARE = ["TIMP3.SA", "TESO", "VIVT4.SA"];
const PURCHASED_AMOUNT = 200;
const PURCHASED_AT = "2021-01-08";
const FROM_DATE = "2021-01-08";
const TO_DATE = "2021-01-20";

export {
  QUOTE_ACT,
  QUOTE_ACT_GAINS,
  QUOTE_ACT_COMPARE,
  INVALID_QUOTE_ACT,
  LIST_QUOTE_COMPARE,
  PURCHASED_AMOUNT,
  PURCHASED_AT,
  FROM_DATE,
  TO_DATE,
};
