const QUOTE_ACT = "PETR4.SA";
const INVALID_QUOTE_ACT = "PETR432.SA";
const LIST_QUOTE_COMPARE = ["TIMP3.SA", "VIVT4.SA", "VALE5.SA"];
const PURCHASED_AMOUNT = 100;
const PURCHASED_AT = "2021-01-05";
const FROM_DATE = "2021-01-04";
const TO_DATE = "2021-01-20";

export {
  QUOTE_ACT,
  INVALID_QUOTE_ACT,
  LIST_QUOTE_COMPARE,
  PURCHASED_AMOUNT,
  PURCHASED_AT,
  FROM_DATE,
  TO_DATE,
};
