name: ci

on: [push]

jobs:
  vm-job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Setup Node 10.20.1
      uses: actions/setup-node@v1
      with:
        node-version: 10.20.1

    - name: Set up Ruby 2.6.6
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6.6
        working-directory: ruby/app
        bundler-cache: true

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - name: Yarn package cache
      uses: actions/cache@v2
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install yarn dependencies
      run: |
        cd ruby/app
        yarn install

    - name: Setup database
      run: |
        cd ruby/app
        bundle exec rake db:setup

    - name: Run tests
      run: |
        cd ruby/app
        bundle exec rspec

    - name: Run rubocop
      run: |
        cd ruby/app
        bundle exec rubocop